### ISSUE TITLE
"no module named woocommerce"

### ISSUE THREAD

**Issue by platzhersh** [OCA/connector-woocommerce#12]
I get this when trying to install the add-on on odoo 8.0

File "/var/lib/odoo/addons/8.0/connector_woocommerce/**init**.py", line 22, in <module>
    from . import model
  File "/var/lib/odoo/addons/8.0/connector_woocommerce/model/**init**.py", line 22, in <module>
    from . import backend
  File "/var/lib/odoo/addons/8.0/connector_woocommerce/model/backend.py", line 23, in <module>
    from woocommerce import API
ImportError: No module named woocommerce

**Comment by Vassy** [comment]
pip install woocommerce

**Comment by maricarlortiz** [comment]
even if I use pip install woocommerce I still get this error. 

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 439, in old_api
    result = new_api(recs, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 443, in new_api
    result = [method(rec, _args, *_kwargs) for rec in self]
  File "/opt/odoo/odoo-server/openerp/addons/base/module/wizard/base_module_update.py", line 15, in update_module
    self.updated, self.added = self.env['ir.module.module'].update_list()
  File "/opt/odoo/odoo-server/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 508, in new_api
    result = method(self._model, cr, uid, _args, *_old_kwargs)
  File "/opt/odoo/odoo-server/openerp/addons/base/module/module.py", line 651, in update_list
    handler.load_addons()
  File "/opt/odoo/odoo-server/openerp/http.py", line 1310, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/opt/odoo/odoo-server/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/odoo/.local/share/Odoo/addons/8.0/connector_woocommerce/**init**.py", line 22, in <module>
    from . import model
  File "/opt/odoo/.local/share/Odoo/addons/8.0/connector_woocommerce/model/**init**.py", line 22, in <module>
    from . import backend
  File "/opt/odoo/.local/share/Odoo/addons/8.0/connector_woocommerce/model/backend.py", line 23, in <module>
    from woocommerce import API
ImportError: No module named woocommerce

**Comment by parthivgls** [comment]
seems like pip install woocommerce is not working for you.
Can you try sudo easy_install woocommerce

**Comment by Flightfreak** [comment]
I've tried both pip and easy_install and they install fine (that is without any faults) but i still get `Unable to install module "connector_woocommerce" because an external dependency is not met: No module named woocommerce`

Any hints too what else could be going wrong?

**Comment by maricarlortiz** [comment]
I also tried pip and easy_install, still got the error then I tried to enter on python and type this:

`from woocommerce import API`

there are no error showing no module name woocommerce unlike what is mention here (http://stackoverflow.com/questions/34892876/installing-woocommerce-connector-in-odoo)

but I still got the error when I tried to install it again, then, I tried it again with this:

```
from woocommerce import API

wcapi = API(
    url="http://example.com",
    consumer_key="ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 
    consumer_secret="cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
)

```

I put my generated woocommerce consumer_key and consumer_secret key to the above code.

it worked, I have installed the connector without the error.

BUT when I tried to connect it to my woocommerce, I got and invalid timestamp error:

> Invalid timestamp
> woocommerce_api_authentication_error

Do you have an idea how to fix this?

**Comment by IT19237114** [comment]
I'm having the same issue. why is github allowing others to close an issue when it's not closed??? Really frustating
