### ISSUE TITLE
cant install in odoo 9

### ISSUE THREAD

**Issue by Washil** [OCA/connector-woocommerce#15]
Hello, I am new in odoo
I have successfully installed odoo 9 on CentOS 7
I tried downloading connector-woocommerce and all deppendecy.
I uploaded to the directory /usr/lib/python2.7/site-packages/openerp/addons/
then I have been doing "sudo easy_install woocomerce" as described in tutuorial techreceptives.
when I installed from the Apps menu,
Error appears as follows.
`Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 385, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 852, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 939, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 802, in parse
    self.parse(rec, mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 805, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/usr/lib/python2.7/site-packages/openerp/tools/convert.py", line 709, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1119, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4132, in create
    record = self.browse(self._create(old_vals))
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/models.py", line 4270, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 139, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "null value in column "act_from" violates not-null constraint
DETAIL:  Failing row contains (17, 1, 2016-02-09 16:14:17.39745, 10, order_confirm, null, 1, null, null, 2016-02-09 16:14:17.39745, null, null, test_exceptions()).
" while parsing /usr/lib/python2.7/site-packages/openerp/addons/sale_exceptions/sale_workflow.xml:4, near
<record id="sale.trans_draft_router" model="workflow.transition">
            <field name="signal">order_confirm</field>
            <field name="condition">test_exceptions()</field>
        </record>`

Kindly its support, thanks in advance.

**Comment by musiq021** [comment]
Same issue here. Looks like it's getting hung up installing the sale_exceptions module.

**Comment by parthivgls** [comment]
dependent modules are still not migrated to v9.

**Comment by IgnacioMelendrez** [comment]
Hello,
I have understood that WooCommerce is available only for version 8 of Odoo.
I was also testing with Odoo 9 and me out mistakes.
regards

**Comment by ingefox** [comment]
That means this connector doesn't work on odoo 9.0 .. isn't it ?

**Comment by pedrobaeza** [comment]
Yeah, the module is not migrated to v9, so it doesn't work in this version until it is.

**Comment by elbafa33** [comment]
Hello every one,
I can't install the module that I've created, I have odoo v9 on centos 7, when I try to install there is an error:

"Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
    result = self._call_function(*_self.params)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(_a, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call__
    return self.method(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in response_wrap
    response = f(_args, *_kw)
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/openerp/addons/base/module/wizard/base_module_upgrade.py", line 87, in upgrade_module
    openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in load_marked_modules
 loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 123, in load_module_graph
    load_openerp_module(package.name)
  File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 324, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line 61, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/usr/lib/python2.7/site-packages/openerp/addons/openacademy/**init**.py", line 2, in <module>
    from . import controllers
ImportError: cannot import name controllers"

THANK YOU FOR YOUR HELP

**Comment by parthivgls** [comment]
It's still work in progress for Odoo v9.

On Fri, May 27, 2016 at 4:37 PM, elbafa33 notifications@github.com wrote:

> Hello every one,
> I can't install the module that I've created, I have odoo v9 on centos 7,
> when I try to install there is an error:
> 
> "Odoo Server Error
> 
> Traceback (most recent call last):
> File "/usr/lib/python2.7/site-packages/openerp/http.py", line 643, in
> 
> _handle_exception return super(JsonRequest,
> self).handle_exception(exception) File
> "/usr/lib/python2.7/site-packages/openerp/http.py", line 680, in dispatch
> result = self._call_function(_self.params) File
> "/usr/lib/python2.7/site-packages/openerp/http.py", line 316, in
> _call_function return checked_call(self.db, _args, *kwargs) File
> "/usr/lib/python2.7/site-packages/openerp/service/model.py", line 118, in
> wrapper return f(dbname, args, *kwargs) File
> "/usr/lib/python2.7/site-packages/openerp/http.py", line 309, in
> checked_call result = self.endpoint(a, *kw) File
> "/usr/lib/python2.7/site-packages/openerp/http.py", line 959, in __call_
> return self.method(_args, *_kw)
> File "/usr/lib/python2.7/site-packages/openerp/http.py", line 509, in
> response_wrap
> response = f(_args, *_kw)
> File
> "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py",
> line 896, in call_button
> action = self.
> 
> _call_kw(model, method, args, {}) File
> "/usr/lib/python2.7/site-packages/openerp/addons/web/controllers/main.py",
> line 884, in call_kw return getattr(request.registry.get(model),
> method)(request.cr http://request.cr, request.uid, args, *kwargs) File
> "/usr/lib/python2.7/site-packages/openerp/api.py", line 250, in wrapper
> return old_api(self, args, *kwargs) File
> "/usr/lib/python2.7/site-packages/openerp/addons/base/module/wizard/base_module_upgrade.py",
> line 87, in upgrade_module
> openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
> File "/usr/lib/python2.7/site-packages/openerp/modules/registry.py", line
> 386, in new openerp.modules.load_modules(registry._db, force_demo, status,
> update_module) File
> "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 338, in
> load_modules loaded_modules, update_module) File
> "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 237, in
> load_marked_modules loaded, processed = load_module_graph(cr, graph,
> progressdict, report=report, skip_modules=loaded_modules,
> perform_checks=perform_checks) File
> "/usr/lib/python2.7/site-packages/openerp/modules/loading.py", line 123, in
> load_module_graph load_openerp_module(package.name http://package.name)
> File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line
> 324, in load_openerp_module __import_('openerp.addons.' + module_name)
> File "/usr/lib/python2.7/site-packages/openerp/modules/module.py", line
> 61, in load_module
> mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
> File "/usr/lib/python2.7/site-packages/openerp/addons/openacademy/_init_.py",
> line 2, in
> from . import controllers
> ImportError: cannot import name controllers"
> 
> THANK YOU FOR YOUR HELP
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/OCA/connector-woocommerce/issues/15#issuecomment-222120442,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACvHWI2q1365N7xTd6-YH24Au_XuuExOks5qFtBlgaJpZM4HWMrT
> .

## 

Thanks & Regards,
Parthiv Patel

**Comment by elbafa33** [comment]
Thank you Mr parthivgls, it means that in odoo v9 it's impossible to create my own modules?

**Comment by parthivgls** [comment]
You have to wait till we finish the migration, then you'll be able to
properly install the module and sync it with your store.

On Fri, May 27, 2016 at 4:58 PM, elbafa33 notifications@github.com wrote:

> Thank you Mr parthivgls, it means that in odoo v9 it's impossible to
> create my own modules?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/OCA/connector-woocommerce/issues/15#issuecomment-222123876,
> or mute the thread
> https://github.com/notifications/unsubscribe/ACvHWEqHTZgAY1iSFrnijIrt5ozGjC5sks5qFtV5gaJpZM4HWMrT
> .

## 

Thanks & Regards,
Parthiv Patel

**Comment by elbafa33** [comment]
Ok thank you mr parthivgls

**Comment by Shamailaafzal** [comment]
models.py:

from openerp import models, fields, api

class SeicoPartner(models.Model):
_name  = 'res.partner'
_inherit  = 'res.partner'

no_of_ac = fields.Integer('No of AC', default=0)
review = fields.Char('Company Review')
view.xml:

  <record id="res_partner_field_ac" model="ir.ui.view">
      <field name="no_of_ac">10</field>

</record>
While installing my own created module it gives

**Comment by ghost** [comment]
Code: 
![untitled](https://cloud.githubusercontent.com/assets/20470853/16865069/81b92808-4a7b-11e6-91c7-4cd93f638e9a.png)
Error while installing new module
![untitled2](https://cloud.githubusercontent.com/assets/20470853/16865125/de49201e-4a7b-11e6-9ee7-5926e82d86a4.png)

**Comment by sgucci1** [comment]
Hello parthivgls

Do you anticipate a date when the migration will be finished?

Thank you

**Comment by djeraseit** [comment]
please correct your readme to not say 100% compatible with Odoo / OpenERP 10.0

**Comment by sgucci1** [comment]
I'm not sure what you mean.  I'm not a developer.

We are using a connector though.  Would you like me to forward this to 
the connector developer?

Steve

> Theodis Butler <mailto:notifications@github.com>
> Wednesday, October 26, 2016 2:48 PM
>
> please correct your readme to not say 100% compatible with Odoo / 
> OpenERP 10.0
>
> —
>

**Comment by djeraseit** [comment]
@sgucci1 yes please. what version of odoo are you using the connector with?
